##### ROOMS #######
POST http://localhost:4004/odata/v4/catalog/Rooms
Content-Type: application/json

{
  "RoomNo":"No-A1",
  "BedTypes":"Single",
  "Price":1100,
  "AC_type":"YES",
  "Shareble":false,
  "Currency":"USD",
  "NoOfPersons":2,
  "BranchCode":"KT004",
  "CompanyCode":"RCR",
  "roomPhotos":"data:image/png;base64,idummy",
  "BookingFlag":true,
  "description":"Raichur Rooms"
}




#### create a room 1st
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "TestRoom",
  "BedTypes": "Single",
  "Price": 1000,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "BookingFlag": true,
  "description": "Room for image testing"
}


####
POST http://localhost:4004/odata/v2/catalog/uploadImage
Content-Type: application/json

{
  "ID": "f1e560cb-0124-4590-aa7e-a75330db7cc3",
  "imageData": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
}


####
POST http://localhost:4004/odata/v2/catalog/getRoomImage
Content-Type: application/json

{
   "ID": "f1e560cb-0124-4590-aa7e-a75330db7cc3"
}



####
GET http://localhost:4004/odata/v2/catalog/Rooms(guid'f1e560cb-0124-4590-aa7e-a75330db7cc3')
Accept: application/json

####################################################################
####################################################################
POST http://localhost:4004/odata/v2/catalog/uploadImage
Content-Type: application/json

{
  "ID": "f1e560cb-0124-4590-aa7e-a75330db7cc3",
  "imageData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
}


###
POST http://localhost:4004/odata/v2/catalog/getRoomImage
Content-Type: application/json

{
  "ID": "f1e560cb-0124-4590-aa7e-a75330db7cc3"
}

###
GET http://localhost:4004/odata/v2/catalog/Rooms(guid'f1e560cb-0124-4590-aa7e-a75330db7cc3')
Accept: application/json

####################################################################



####
GET http://localhost:4004/odata/v2/catalog/getRoomPhoto?ID=guid'7c084021-7d5f-464d-87b0-1d0ccc78d176'



############################################
############################################
############################################
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "NewTestRoom",
  "BedTypes": "Single",
  "Price": 1500,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "BookingFlag": true,
  "description": "New room Mateen testing"
}
###
POST http://localhost:4004/odata/v2/catalog/uploadImage
Content-Type: application/json

{
  "ID": "b5f77da1-a94d-448e-8f7d-40af664ea883",
  "imageData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
}




#####
GET http://localhost:4004/odata/v4/catalog/getRoomPhoto(ID=7c084021-7d5f-464d-87b0-1d0ccc78d176)



######
GET http://localhost:4004/odata/v2/catalog/getRoomPhoto?ID=guid'7c084021-7d5f-464d-87b0-1d0ccc78d176'




####
POST http://localhost:4004/odata/v2/catalog/uploadImage
Content-Type: application/json

{
  "ID": "7c084021-7d5f-464d-87b0-1d0ccc78d176",
  "imageData": "data:image/png;base64,dummy"
}


###
GET http://localhost:4004/odata/v2/catalog/Rooms(guid'7c084021-7d5f-464d-87b0-1d0ccc78d176')
Accept: application/json


############################################
############################################
############################################

##### png small
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "Test-Room",
  "BedTypes": "Single",
  "Price": 1000,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "roomPhotos": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "BookingFlag": true,
  "description": "Test room with image"
}


#### png
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "PNG-Test",
  "BedTypes": "Single",
  "Price": 1000,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "roomPhotos": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "BookingFlag": true,
  "description": "Test with PNG image"
}

##### jpeg
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "JPEG-Test",
  "BedTypes": "Single",
  "Price": 1000,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "roomPhotos": "data:image/png;base64,iVBORw0KGgo=",
    "BookingFlag": true,
  "description": "Test with JPEG image"
}



####
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "StreamTest",
  "BedTypes": "Single",
  "Price": 1000,
  "AC_type": "YES", 
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "roomPhotos": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "BookingFlag": true,
  "description": "Test stream handling"
}

####
POST http://localhost:4004/odata/v2/catalog/Rooms
Content-Type: application/json

{
  "RoomNo": "Debug-Test-2",
  "BedTypes": "Single", 
  "Price": 1000,
  "AC_type": "YES",
  "Shareble": false,
  "Currency": "INR",
  "NoOfPersons": 2,
  "BranchCode": "KT001",
  "CompanyCode": "KLBG",
  "roomPhotos": "test-simple-string",
  "BookingFlag": true,
  "description": "Debug test with simple string"
}


###
GET http://localhost:4004/odata/v4/catalog/Rooms
Content-Type: application/json


#### Payment ######

POST http://localhost:4004/odata/v4/catalog/Payment
Content-Type: application/json

{
      "Date"          : "2025-03-02",
      "BankName"      : "SBI",
      "Amount"        : 5023.12,
      "Mode"          : "online",
      "TransactionID" : "TR-1237",
      "Currency"      : "INR"
}

###
GET http://localhost:4004/odata/v4/catalog/Payment
Content-Type: application/json

#### Booking ######

POST http://localhost:4004/odata/v4/catalog/Booking
Content-Type: application/json

{
 
      "NoOfPersons" : 10,
      "StartDate"   : "2024-03-03",
      "EndDate"     : "2024-03-16",
      "BookingDate" : "2024-03-01",
      "CancelDate"  : "2024-03-20",
      "PaymentType" :"online",
      "Status"      : "APV"
}

###
GET http://localhost:4004/odata/v4/catalog/Booking
Content-Type: application/json

#### Customer ####

POST http://localhost:4004/odata/v4/catalog/Customer
Content-Type: application/json

{
 
      "Salutation"       : "Mr",
      "CustomerName"     : "Raj",
      "Gender"           : "Male",
      "DateOfBirth"      : "2004-11-03",
      "PermanentAddress" : "Mumbai",
      "Country"          : "India",
      "State"            : "MH",
      "CountryCode"      : "INR",
      "City"             : "Pune",
      "STDCode"          : "+91",
      "MobileNo"         : "1234567390",
      "CustomerEmail"    : "raj@gmail.com"
}

###
GET http://localhost:4004/odata/v4/catalog/Customer
Content-Type: application/json


#### Customer ####

POST http://localhost:4004/odata/v4/catalog/CustomerDocument
Content-Type: application/json

{
      "DocumentType" : "PDF",
      "FileName"     : "photo",
      "FileType"     : "mim"
}

###
GET http://localhost:4004/odata/v4/catalog/CustomerDocument
Content-Type: application/json


#### Login ####

POST http://localhost:4004/odata/v4/catalog/Login
Content-Type: application/json

{
      "EmployeeName" : "pk",
      "Role"         : "emp",
      "EmailID"      : "pk@gmail.com",
      "OTP"          : "123456",
      "Password"     : "12345",
      "BranchCode"   : "KL-101",
      "CompanyCode"  : "KT-1001",
      "TimeDate"     : "2025-09-02",
      "MobileNo"     : "1234531234"
}

###
GET http://localhost:4004/odata/v4/catalog/Login
Content-Type: application/json

#### Employee ####

POST http://localhost:4004/odata/v4/catalog/Employee
Content-Type: application/json

{
      "Role"                  : "Employee",
      "Salutation"            : "Mr",
      "EmployeeName"          : "bob",
      "FatherName"            : "dummy",
      "Gender"                : "male",
      "DateOfBirth"           : "2003-09-07",
      "CompanyEmailID"        : "bob@gmail.com",
      "PermanentAddress"      :"pune",
      "CorrespondenceAddress" : "pune",
      "Country"               : "India",
      "State"                 : "MH",
      "CountryCode"           : "INR",
      "BaseLocation"          : "KL-101",
      "BloodGroup"            : "O+",
      "ManagerName"           : "Datti",
      "Designation"           : "jr.developer",
      "STDCode"               : "+91",
      "MobileNo"              : "1234567890"
}

###
GET http://localhost:4004/odata/v4/catalog/Employee
Content-Type: application/json


### Upload Image (Base64)
POST http://localhost:4004/odata/v4/catalog/uploadImage
Content-Type: application/json

{
  "ID": "7bf064dc-baac-423f-a80f-d3e90636dec0",
  "imageData": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhURExMWFhUXGBgaGBgYGBsaGhgYGBkYGBgYGhgcHSggGBolHRgYITEhJSkrLi4uGB8zODMtNygtLisBCgoKDg0OGxAQGy0lICYtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAJ8BPgMBIgACEQEDEQH/xAAaAAEAAwEBAQAAAAAAAAAAAAAAAQIDBAUG/8QAKxAAAgEDAgQEBwAAAAAAAAAAAAECAwQRAAUSIRMxQQYiUWGBodETIzNC/8QAFgEBAQEAAAAAAAAAAAAAAAAAAgAB/8QAGBEBAQEBAQAAAAAAAAAAAAAAAAECASH/2gAMAwEAAhEDEQA/AOfR5yXFKzJ6ZAb9SoYyaHQeRbF3IMoDn0/Nnkr3YxJ7Q80uKjaCwslQmSxNYeo/W2R4LKbyRHUbg13xNnNh1hLFwbhVrYpQ9Q2iHdMkbzrb7kMuYmWeY5J47GNLlPaAXXJ2Ob5xgD5x0xScQbd4VqViP/2Q=="
}

### Delete all rooms
POST http://localhost:4004/odata/v4/catalog/deleteAllRooms
Content-Type: application/json